---
functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и получать подробную информацию о них
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать ее содержимое
 - Пользователь должен иметь возможность переключать язык интерфейса

нефункциональное:
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию
 - Сайт необходимо протестировать на совместимость с последними версиями браузеров
 - Важно, чтобы сайт мог обрабатывать большой объем трафика
 - Сайт должен быть доступен на различных устройствах
 - Сайт должен быть локализован (переведен) на русский и английский языки
неявное:
 - Сайт должен быть разработан с учетом удобства использования и оптимизирован для быстрой работы
 - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
